name=boost-embedded-190
version=1.90.0
author=Boost contributors
maintainer=SAT <innovation@sat.qc.ca>
sentence=boost for embedded systems
paragraph=This library provides boost 1.90 for embedded systems
category=Device Control
url=https://boost.org
architectures=*

